--- dbpg.h.org	2025-12-03 16:37:40.171256167 +0800
+++ dbpg.h	2025-12-03 16:37:58.707205142 +0800
@@ -25,7 +25,7 @@
  * pg_config.h. However, the PACKAGE_* macros conflict with
  * NaviServer's packaging information, so we drop these.
  */
-#include <pg_config.h>
+#include <pgsql/pg_config.h>
 #undef PACKAGE_VERSION
 #undef PACKAGE_TARNAME
 #undef PACKAGE_STRING
@@ -34,7 +34,7 @@
 #undef PACKAGE_URL
 
 #include <nsdb.h>
-#include <libpq-fe.h>
+#include <pgsql/libpq-fe.h>
 
 /*
  * Forward compatibility, in case a new version of the module is compiled
--- Makefile.org	2025-12-03 16:39:07.524319290 +0800
+++ Makefile	2025-12-03 16:39:23.699037548 +0800
@@ -27,7 +27,7 @@
 # version of this file under either the License or the GPL.
 
 ifndef NAVISERVER
-    NAVISERVER  = /usr/local/ns
+    NAVISERVER  = /var/lib/naviserver
 endif
 
 #
